### ISSUE TITLE
Account login?

### ISSUE THREAD

**Issue by snoge** [kennelbound-smartthings/kevo-unofficial#1]
where to enter login details?

![34651770-c216be5a-f3cc-11e7-88a1-09accfe82b1d](https://user-images.githubusercontent.com/7465378/34822839-30865332-f6c0-11e7-94f8-a59972357782.jpg)

**Comment by ssshake** [comment]
see the readme as this is all done in the web browser not the app.

**Comment by kennelbound-smartthings** [comment]
Closing.  You configure through the device preferences.
